//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosEntidad {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Decopack.EE.Recursos.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a comprador dni.
        /// </summary>
        public static string comprador_dni {
            get {
                return ResourceManager.GetString("comprador_dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domicilio.
        /// </summary>
        public static string comprador_domicilio {
            get {
                return ResourceManager.GetString("comprador_domicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Socio.
        /// </summary>
        public static string comprador_socioestado {
            get {
                return ResourceManager.GetString("comprador_socioestado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion Del Deposito.
        /// </summary>
        public static string deposito_detalle {
            get {
                return ResourceManager.GetString("deposito_detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deposito.
        /// </summary>
        public static string empleado_coddeposito {
            get {
                return ResourceManager.GetString("empleado_coddeposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string empleado_detalle {
            get {
                return ResourceManager.GetString("empleado_detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Ingreso.
        /// </summary>
        public static string empleado_fechadeingreso {
            get {
                return ResourceManager.GetString("empleado_fechadeingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo del Empleado.
        /// </summary>
        public static string envio_codempleadodeposito {
            get {
                return ResourceManager.GetString("envio_codempleadodeposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo del Envio.
        /// </summary>
        public static string envio_codenvio {
            get {
                return ResourceManager.GetString("envio_codenvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de la Venta.
        /// </summary>
        public static string envio_codventa {
            get {
                return ResourceManager.GetString("envio_codventa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion.
        /// </summary>
        public static string envio_direccion {
            get {
                return ResourceManager.GetString("envio_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string envio_estado {
            get {
                return ResourceManager.GetString("envio_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Llegada.
        /// </summary>
        public static string envio_fechadellegada {
            get {
                return ResourceManager.GetString("envio_fechadellegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Salida.
        /// </summary>
        public static string envio_fechadesalida {
            get {
                return ResourceManager.GetString("envio_fechadesalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobado.
        /// </summary>
        public static string pedido_aprobado {
            get {
                return ResourceManager.GetString("pedido_aprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string pedido_cantidad {
            get {
                return ResourceManager.GetString("pedido_cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Comprador.
        /// </summary>
        public static string pedido_codcomprador {
            get {
                return ResourceManager.GetString("pedido_codcomprador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo del Pedido.
        /// </summary>
        public static string pedido_codigo {
            get {
                return ResourceManager.GetString("pedido_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Producto.
        /// </summary>
        public static string pedido_codproducto {
            get {
                return ResourceManager.GetString("pedido_codproducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string pedido_descripcion {
            get {
                return ResourceManager.GetString("pedido_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string pedido_estado {
            get {
                return ResourceManager.GetString("pedido_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string pedido_fecha {
            get {
                return ResourceManager.GetString("pedido_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo.
        /// </summary>
        public static string pedido_logo {
            get {
                return ResourceManager.GetString("pedido_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        public static string pedido_monto {
            get {
                return ResourceManager.GetString("pedido_monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string persona_apellido {
            get {
                return ResourceManager.GetString("persona_apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string persona_email {
            get {
                return ResourceManager.GetString("persona_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string persona_estado {
            get {
                return ResourceManager.GetString("persona_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string persona_nombre {
            get {
                return ResourceManager.GetString("persona_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        public static string persona_telefono {
            get {
                return ResourceManager.GetString("persona_telefono", resourceCulture);
            }
        }
    }
}
