//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Decopack.Web.Recursos.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobado.
        /// </summary>
        public static string aprobado {
            get {
                return ResourceManager.GetString("aprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string aprobar {
            get {
                return ResourceManager.GetString("aprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Areas.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar.
        /// </summary>
        public static string asignar {
            get {
                return ResourceManager.GetString("asignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DecoPacks es una empresa argentina con 2 años en el mercado, dedicada a cubrir la demanda del diseño de packaging primario y secundario orientado a la cosmética para su posterior producción.
        ///Está formada por un grupo de emprendedores unidos con un objetivo común: mejorar la imagen de su producto. Si necesita dar con una empresa especializada en el diseño de packaging y/o asesorarte en la creación del contenedor para tu producto buscando una firme imagen que le dé atractivo, DecoPacks es sin dudas lo que ne [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string bienvenida1 {
            get {
                return ResourceManager.GetString("bienvenida1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra empresa, Decopacks, pretende convertirse en una empresa de referencia en la parte del diseño de packaging en el ámbito de cosmética de la argentina mediante nuestra dedicación, esfuerzo, compromiso, innovación y buena imagen ante los clientes. Para ello, tenemos propuesto lograr una expansión a diferentes partes de la región de argentina mediante varias sucursales, para lograr satisfacer la demanda de nuestros clientes de diferentes localizaciones. También estaríamos enfocados en satisfacer la deman [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string bienvenida2 {
            get {
                return ResourceManager.GetString("bienvenida2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La industria de cosmética se destaca por una exigencia en cuanto al diseño de sus contenedores, por lo que, el packaging debe tener un atractivo hacia el cliente, ya que la mayor parte de la razón de su venta es el impacto que este cause en el cliente basado en su diseño.
        ///Decopacks principalmente se destaca de sus competidores, gracias a sus diseños innovadores de los productos mediante la utilización de programas de alta calidad orientado a la edición y su asesoramiento personalizado en la parte de la cre [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string bienvenida3 {
            get {
                return ResourceManager.GetString("bienvenida3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra empresa Decopacks se dedica a brindar soluciones de packaging de productos del área de la cosmética, por lo cual, está enfocado a realizar soluciones innovadoras en el área de diseño de sus productos para lograr una mejor imagen de este ante los consumidores de nuestro cliente y que permita un aumento considerable de sus ventas. Los clientes de nuestra empresa se los puede definir como empresas intermedias que buscan una mejor visión de su producto ante el público. Ante esto, concentramos nuestro es [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string bienvenida4 {
            get {
                return ResourceManager.GetString("bienvenida4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a la pagina principal de la empresa de packaging DecoPacks.
        /// </summary>
        public static string bienvenida5 {
            get {
                return ResourceManager.GetString("bienvenida5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para mas opciones por favor inicie sesion.
        /// </summary>
        public static string bienvenida6 {
            get {
                return ResourceManager.GetString("bienvenida6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueado.
        /// </summary>
        public static string bloqueado {
            get {
                return ResourceManager.GetString("bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string buscar {
            get {
                return ResourceManager.GetString("buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por DNI.
        /// </summary>
        public static string buscarpordni {
            get {
                return ResourceManager.GetString("buscarpordni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar y Volver.
        /// </summary>
        public static string cancelaryvolver {
            get {
                return ResourceManager.GetString("cancelaryvolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string cantidad {
            get {
                return ResourceManager.GetString("cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalogo.
        /// </summary>
        public static string catalogo {
            get {
                return ResourceManager.GetString("catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aqui se muestra el catalogo de productos para comprar. Para realizar el pedido se debe estar registrado en el sistema..
        /// </summary>
        public static string catalogo1 {
            get {
                return ResourceManager.GetString("catalogo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalogo de Productos:.
        /// </summary>
        public static string catalogodeproductos {
            get {
                return ResourceManager.GetString("catalogodeproductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesion.
        /// </summary>
        public static string cerrar {
            get {
                return ResourceManager.GetString("cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprador.
        /// </summary>
        public static string comprador {
            get {
                return ResourceManager.GetString("comprador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string confirmar {
            get {
                return ResourceManager.GetString("confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string crear {
            get {
                return ResourceManager.GetString("crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De.
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decopacks.
        /// </summary>
        public static string decopacks {
            get {
                return ResourceManager.GetString("decopacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deposito.
        /// </summary>
        public static string deposito {
            get {
                return ResourceManager.GetString("deposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseño y Fabricacion de Packaging.
        /// </summary>
        public static string DiseñoyFabricacion {
            get {
                return ResourceManager.GetString("DiseñoyFabricacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI del Comprador.
        /// </summary>
        public static string dnicomprador {
            get {
                return ResourceManager.GetString("dnicomprador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado.
        /// </summary>
        public static string empleado {
            get {
                return ResourceManager.GetString("empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidades.
        /// </summary>
        public static string Entidades {
            get {
                return ResourceManager.GetString("Entidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al Decopack, Inicie sesion:.
        /// </summary>
        public static string entrar1 {
            get {
                return ResourceManager.GetString("entrar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envio.
        /// </summary>
        public static string envio {
            get {
                return ResourceManager.GetString("envio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignacion del Envio se Realizo con Exito.
        /// </summary>
        public static string envio1 {
            get {
                return ResourceManager.GetString("envio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se confirmo el envio con exito.
        /// </summary>
        public static string envio2 {
            get {
                return ResourceManager.GetString("envio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta es la pagina para asignar los envios pendientes al empleado de entrega..
        /// </summary>
        public static string envioasignar1 {
            get {
                return ResourceManager.GetString("envioasignar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Envio:.
        /// </summary>
        public static string envioasignar2 {
            get {
                return ResourceManager.GetString("envioasignar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aqui se ven los estados de los envios recibidos.
        /// </summary>
        public static string envioestadoenvio1 {
            get {
                return ResourceManager.GetString("envioestadoenvio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Envio:.
        /// </summary>
        public static string envioestadoenvio2 {
            get {
                return ResourceManager.GetString("envioestadoenvio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aca se muestran todos los envios de los pedidos de los compradores. Cuando llega un pedido se lo asigna a un empleado y el empleado confirma la llegada del producto..
        /// </summary>
        public static string envioindex1 {
            get {
                return ResourceManager.GetString("envioindex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Envios:.
        /// </summary>
        public static string envioindex2 {
            get {
                return ResourceManager.GetString("envioindex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aqui se visualizan los envios asignados al empleado. Entrega el producto y se confirma para finalizar cada envio..
        /// </summary>
        public static string envioindexempleado1 {
            get {
                return ResourceManager.GetString("envioindexempleado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Envios:.
        /// </summary>
        public static string envioindexempleado2 {
            get {
                return ResourceManager.GetString("envioindexempleado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hacer Pedido.
        /// </summary>
        public static string hacerpedido {
            get {
                return ResourceManager.GetString("hacerpedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola.
        /// </summary>
        public static string hola {
            get {
                return ResourceManager.GetString("hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inconveniente.
        /// </summary>
        public static string inconveniente {
            get {
                return ResourceManager.GetString("inconveniente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        public static string iniciar {
            get {
                return ResourceManager.GetString("iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Pedidos.
        /// </summary>
        public static string listapedidos {
            get {
                return ResourceManager.GetString("listapedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Materia Prima.
        /// </summary>
        public static string materiaprima {
            get {
                return ResourceManager.GetString("materiaprima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Materia Prima - Producto.
        /// </summary>
        public static string materiaprimaproducto {
            get {
                return ResourceManager.GetString("materiaprimaproducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Materia Prima - Proveedor.
        /// </summary>
        public static string materiaprimaproveedor {
            get {
                return ResourceManager.GetString("materiaprimaproveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si Necesitas Ayuda Clic Aqui.
        /// </summary>
        public static string mensajeayuda {
            get {
                return ResourceManager.GetString("mensajeayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Envios.
        /// </summary>
        public static string misenvios {
            get {
                return ResourceManager.GetString("misenvios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Pedidos.
        /// </summary>
        public static string mispedidos {
            get {
                return ResourceManager.GetString("mispedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        public static string monto {
            get {
                return ResourceManager.GetString("monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Producto.
        /// </summary>
        public static string nombreproducto {
            get {
                return ResourceManager.GetString("nombreproducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operaciones Principales.
        /// </summary>
        public static string OperacionesPrincipales {
            get {
                return ResourceManager.GetString("OperacionesPrincipales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        public static string pagar {
            get {
                return ResourceManager.GetString("pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagina.
        /// </summary>
        public static string pagina {
            get {
                return ResourceManager.GetString("pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel Admin.
        /// </summary>
        public static string paneladmin {
            get {
                return ResourceManager.GetString("paneladmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido.
        /// </summary>
        public static string pedido {
            get {
                return ResourceManager.GetString("pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Pedido se Aprobo con Exito.
        /// </summary>
        public static string pedido1 {
            get {
                return ResourceManager.GetString("pedido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Pedido se Pago con Exito.
        /// </summary>
        public static string pedido2 {
            get {
                return ResourceManager.GetString("pedido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Pedido se Pago con Exito.
        /// </summary>
        public static string pedido3 {
            get {
                return ResourceManager.GetString("pedido3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar Pedido:.
        /// </summary>
        public static string pedidoaprobar1 {
            get {
                return ResourceManager.GetString("pedidoaprobar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este es el formulario es para aprobar un pedido. El empleado ingresa el monto del trabajo segun el pedido..
        /// </summary>
        public static string pedidoaprobarh {
            get {
                return ResourceManager.GetString("pedidoaprobarh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Pedido:.
        /// </summary>
        public static string pedidocrear1 {
            get {
                return ResourceManager.GetString("pedidocrear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este es el formulario para dar de alta un pedido. Ingrese la cantidad del producto a comprar, la descripcion detallando el trabajo a realizar y opcionalmente un logo para el producto..
        /// </summary>
        public static string pedidocrearh {
            get {
                return ResourceManager.GetString("pedidocrearh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aqui se muestran todos los pedidos que se han realizado en el tiempo. El Pedido es creado por un comprador a la espera de la confirmacion del precio final del empleado. Una vez confirmado el comprador puede realiza el pago para la realizacion de la venta..
        /// </summary>
        public static string pedidoindex1 {
            get {
                return ResourceManager.GetString("pedidoindex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aqui se muestran todos los pedidos que se han realizado en el tiempo. Los pedidos realizados esperan una confirmacion por parte de nuestros empleados para confirmar el precio final del trabajo. Una vez confirmado, se le habilitara el pago del mismo. Una vez pagado puede mirar el estao del envio del producto comprado a su domicilio..
        /// </summary>
        public static string pedidoindexusuario1 {
            get {
                return ResourceManager.GetString("pedidoindexusuario1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Pedidos:.
        /// </summary>
        public static string pedidoindexusuario2 {
            get {
                return ResourceManager.GetString("pedidoindexusuario2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        public static string producto {
            get {
                return ResourceManager.GetString("producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string proveedor {
            get {
                return ResourceManager.GetString("proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string registrarse {
            get {
                return ResourceManager.GetString("registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reposicion.
        /// </summary>
        public static string reposicion {
            get {
                return ResourceManager.GetString("reposicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Reposicion se realizo con Exito.
        /// </summary>
        public static string reposicion1 {
            get {
                return ResourceManager.GetString("reposicion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelacion de Reposicion con Exito.
        /// </summary>
        public static string reposicion2 {
            get {
                return ResourceManager.GetString("reposicion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se Confirmo el Pedido Informando un Problema.
        /// </summary>
        public static string reposicion3 {
            get {
                return ResourceManager.GetString("reposicion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En esta pagina se visualizan las reposiciones. Las reposiciones son generadas por falta de stock de un producto determinado o por una reposicion que realiza un empleado. Al confirmar la reposicion se asegura el recibimiento del mismo. Tambien se puede confirmar la reposicion avisando que hubo problemas con el proveedor del producto..
        /// </summary>
        public static string reposicionindex1 {
            get {
                return ResourceManager.GetString("reposicionindex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Reposicion:.
        /// </summary>
        public static string reposicionindex2 {
            get {
                return ResourceManager.GetString("reposicionindex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creacion de Nueva Cuenta:.
        /// </summary>
        public static string salida1 {
            get {
                return ResourceManager.GetString("salida1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta cuenta ha sido bloqueada, inténtelo de nuevo más tarde..
        /// </summary>
        public static string salida2 {
            get {
                return ResourceManager.GetString("salida2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock de Materia Prima - Deposito.
        /// </summary>
        public static string stockmateriaprimadeposito {
            get {
                return ResourceManager.GetString("stockmateriaprimadeposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Envio.
        /// </summary>
        public static string verenvio {
            get {
                return ResourceManager.GetString("verenvio", resourceCulture);
            }
        }
    }
}
